// Work
work_array = [
  '<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/328106931?h=df95fc8e93&title=0&byline=0&portrait=0&speed=0&badge=0&autopause=0&player_id=0&app_id=58479/embed" class="video" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script><div class="title">夕卜</div><p>/ wài /<br>A study on foreignness, 2019<br><br>Following the 1858 Treaty of Tientsin which granted foreigners the right to travel in China, Russian orientalist Alekseĭ Matveevich Pozdneev led a year-long expedition to China and Mongolia. Pozdneev arrived at a moment when the notion of foreignness was intensely debated. Many of the places he visited exist in my childhood memory only as names. But names are never just names. For instance, <em>Zhangjiakou</em>, also known as <em>Kalgan</em> in Mongolian, summons in both languages the idea of &#39;gate&#39; &mdash; a symbol of border and protection, a separation, a threshold. But doors open upon the mysterious &mdash; doesn’t it also project the scene of passing, an invitaion to cross from one world to another?<br><br>In 2018 I traveled along Pozdneev&#39;s route with POND, an AI trained on translations and capable of annotating images. Our hope is not to pledge allegiance to one history or another, but to develop a way of seeing that can only be understood as foreign and alien.</p>',

  '<img src="./images/work1.jpg"><div class="title">夕卜</div><p>/ wài /<br>A study on foreignness, 2019<br><br>Following the 1858 Treaty of Tientsin which granted foreigners the right to travel in China, Russian orientalist Alekseĭ Matveevich Pozdneev led a year-long expedition to China and Mongolia. Pozdneev arrived at a moment when the notion of foreignness was intensely debated. Many of the places he visited exist in my childhood memory only as names. But names are never just names. For instance, <em>Zhangjiakou</em>, also known as <em>Kalgan</em> in Mongolian, summons in both languages the idea of &#39;gate&#39; &mdash; a symbol of border and protection, a separation, a threshold. But doors open upon the mysterious &mdash; doesn’t it also project the scene of passing, an invitaion to cross from one world to another?<br><br>In 2018 I traveled along Pozdneev&#39;s route with POND, an AI trained on translations and capable of annotating images. Our hope is not to pledge allegiance to one history or another, but to develop a way of seeing that can only be understood as foreign and alien.</p>',

  '<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/481448579?h=93b0e6d624&amp&title=0&byline=0&portrait=0&speed=0&badge=0&autopause=0&player_id=0&app_id=58479/embed" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script><div class="title">Lovers Revolt, Lovers Revolve 1</div><p><em>Lovers Revolt, Lovers Revolve: Stories against dictators, colonizers and all other monsters</em>, features the first chapter of a collaborative serial fiction written by Cici Wu and Xiaofei Mo, their works in this special presentation also expand from texts to drawings and a film. Speculating upon 前世 Past Lives and 來生 Future Lives of Hong Kong, this work explores the relationship between love and revolution. Particularly inspired by the recent transnationally geopolitical struggles, the writers want to suggest another set of languages to uncover the invisible world, to restore a different past and manifest a future towards liberation. Cast of characters in this chapter includes a thousand-year-old immortal girl, a lantern from Khotan, lantern&#39;s shadow, early cinema, a lighthouse, a disappeared island, Xi Xi&#39;s floating city, ghost of cinema, a tooth, a mirror, and time.</p>',

  '<img src="./images/work2.jpg"><div class="title">Lovers Revolt, Lovers Revolve 1</div><p><em>Lovers Revolt, Lovers Revolve: Stories</em> against dictators, colonizers and all other monsters, features the first chapter of a collaborative serial fiction written by Cici Wu and Xiaofei Mo, their works in this special presentation also expand from texts to drawings and a film. Speculating upon 前世 Past Lives and 來生 Future Lives of Hong Kong, this work explores the relationship between love and revolution. Particularly inspired by the recent transnationally geopolitical struggles, the writers want to suggest another set of languages to uncover the invisible world, to restore a different past and manifest a future towards liberation. Cast of characters in this chapter includes a thousand-year-old immortal girl, a lantern from Khotan, lantern&#39;s shadow, early cinema, a lighthouse, a disappeared island, Xi Xi&#39;s floating city, ghost of cinema, a tooth, a mirror, and time.</p>',

  '<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/799674183?h=f69d90bdd2&title=0&byline=0&portrait=0&speed=0&badge=0&autopause=0&player_id=0&app_id=58479/embed" class="video" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script><div class="title">Lovers Revolt, Lovers Revolve 2</div><p><em>Lovers Revolt, Lovers Revolve</em> traverses across the past lives and future lives, with a sentient mirror and a missing tooth playing important roles. The film is the second chapter of <em>Lovers Revolt Lovers Revolve: stories against dictators, colonizers, and all other monsters</em>, a collaborative fiction project with Cici Wu, consisting of video, works on paper, and an on-going series of publications.</p>',

  '<img src="./images/work3.jpg"><div class="title">Lovers Revolt, Lovers Revolve 2</div><p><em>Lovers Revolt, Lovers Revolve</em> traverses across the past lives and future lives, with a sentient mirror and a missing tooth playing important roles. The film is the second chapter of <em>Lovers Revolt Lovers Revolve: stories against dictators, colonizers, and all other monsters</em>, a collaborative fiction project with Cici Wu, consisting of video, works on paper, and an on-going series of publications.</p>',

  '<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/812990780?h=32d5b2b0d9&title=0&byline=0&portrait=0&speed=0&badge=0&autopause=0&player_id=0&app_id=58479/embed" class="video" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen frameborder="0" style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script><div class="title">Willow</div><p>Work in progress</p>',

  '<img src="./images/work4.jpg"><div class="title">Willow</div><p>Work in progress</p>',

  '<img src="./images/work5.jpg"><div class="title">Willow</div><p>Work in progress</p>',
]

function get_random_work(){
  // Get a random index
  random_index = Math.floor(Math.random() * work_array.length);

  // Get code using the random_index
  selected_code = work_array[random_index]

  // Insert the code
  document.getElementById('wrapper').innerHTML = `${selected_code}`
}

// Collaborations
collaborations_array = [
  '<img src="./images/collaborations1-1.jpg"><div class="title">A Seed</div><p class="paragraph">Collective action<br>Public spaces, New York, July 2017<br><br>Mourning and bereavement for a recent death Liu Xiaobo (1955&ndash;2017), with the hope that Liu Xiaobo who had high hopes but took a risky path during his time and suffered for that will be remembered. We organized a seeding memorial in the Socrates Sculpture Park; and placed placards containing Liu Xiaobo&#39;s words around Chinatown in New York.</p>',

  '<img src="./images/collaborations1-2.jpg"><div class="title">A Seed</div><p class="paragraph">Collective action<br>Public spaces, New York, July 2017<br><br>Mourning and bereavement for a recent death Liu Xiaobo (1955&ndash;2017), with the hope that Liu Xiaobo who had high hopes but took a risky path during his time and suffered for that will be remembered. We organized a seeding memorial in the Socrates Sculpture Park; and placed placards containing Liu Xiaobo&#39;s words around Chinatown in New York.</p>',

  '<img src="./images/collaborations3-1.jpg" style="width:50% !important; margin-top:10%; margin-bottom:10%; margin-left:40%;"><div class="title">The Room of Spirit and Time</div><p class="paragraph">Founding memebers of TRST from left to right: Taro Masushio, Ali Van, Cici Wu, Xiaofei Mo, Wang Xu, photo taken on April 28th, 2019, New York.<br><br>The Room of Spirit and Time is initiated by Taro Masushio, Xiaofei Mo, Ali Van, Wang Xu and Cici Wu. Taking the form of collaborative works and events, the first iteration at Queens Museum begins with readings of ancient and medieval Asian texts as a possible means to reimagine and cultivate a romantic epistemology. In this room, both learning and unlearning take place; we invite temporary amnesia, a kind of forgetting and drifting via exercises, recitations, meditations, improvisations... fluid and ephemeral sleepwalking. Along these activities are non - activities, where TRST functions as a hub for leisurely gatherings, for artists and thinkers, dreams and realities, set to a slow flow against the fast rhythms of New York City.<br><br><a href="http://theroomofspiritandtime.info/">link</a></p>',

  '<img src="./images/collaborations3-2.jpg" style="width:50% !important; margin-top:10%; margin-bottom:10%; margin-left:10%;"><div class="title">The Room of Spirit and Time</div><p class="paragraph">Reading of The Book of Mountains and Seas at Catskill Zendo, organized by Ontopo, 2019<br><br>The Room of Spirit and Time is initiated by Taro Masushio, Xiaofei Mo, Ali Van, Wang Xu and Cici Wu. Taking the form of collaborative works and events, the first iteration at Queens Museum begins with readings of ancient and medieval Asian texts as a possible means to reimagine and cultivate a romantic epistemology. In this room, both learning and unlearning take place; we invite temporary amnesia, a kind of forgetting and drifting via exercises, recitations, meditations, improvisations... fluid and ephemeral sleepwalking. Along these activities are non - activities, where TRST functions as a hub for leisurely gatherings, for artists and thinkers, dreams and realities, set to a slow flow against the fast rhythms of New York City.<br><br><a href="http://theroomofspiritandtime.info/">link</a></p>',

  '<img src="./images/collaborations3-3.jpg" style="width:30% !important; margin-top:10%; margin-bottom:10%; margin-left:0%;"><img src="./images/collaborations3-5.jpg" style="width:20% !important; margin-top:30%; margin-bottom:0%; margin-left:10%;"><div class="title">Body So Low<br>The Room of Spirit and Time</div><p class="paragraph">Drawings by visitors, first reading session, 2019<br><br>The process of mourning, for the passing of spirit and time. The blood line keeps merging, flowing, sinking. Breath propelled into motion out of space. All the deaths before us, what flight are you taking?<br><br>TRST invites you to join our first reading session, Body So Low. The text chosen is Traditions of Divine Transcendents, a collection of biographies, or eulogies, attributed to Ge Hong from the 3rd-4th century China, about ordinary human beings on the quest for radical departure. In other words, "They shed their mortal forms and melted away."<br><br>As an obscure and unfamiliar text, Traditions of Divine Transcendents was compiled in the beginning of the formation of Taoism. These practitioners demonstrated the use of matter and process as supposed means of achieving what cannot be simply understood as the obviation of death, but rather to attain an exalted state of existence through assimilating to and connecting with distant realms.The attainment assumed a process of inner studies and enhanced awareness of reality.<br><br>We hope this somehow opaque text could bring thoughts towards imagining questions such as how to act radically; overcoming fear; afterlife of institutions; matter and spirit in consumerism; friendship and kinship in different spaces and temporalities; and together we collect inspirations from the text and celebrate. We are not searching for any solutions in this journey of reading.<br><br>The Room of Spirit and Time is initiated by Taro Masushio, Xiaofei Mo, Ali Van, Wang Xu and Cici Wu. Taking the form of collaborative works and events, the first iteration at Queens Museum begins with readings of ancient and medieval Asian texts as a possible means to reimagine and cultivate a romantic epistemology. In this room, both learning and unlearning take place; we invite temporary amnesia, a kind of forgetting and drifting via exercises, recitations, meditations, improvisations... fluid and ephemeral sleepwalking. Along these activities are non-activities, where TRST functions as a hub for leisurely gatherings, for artists and thinkers, dreams and realities, set to a slow flow against the fast rhythms of New York City.<br><br><a href="./images/BodySoLow_01312019.pdf">PDF</a><br><a href="http://theroomofspiritandtime.info/">link</a></p>',

  '<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/812996554?h=9055eac858&amp&title=0&byline=0&portrait=0&speed=0&badge=0&autopause=0&player_id=0&app_id=58479/embed" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script><div class="title">Cloud Vapor Star<br>The Room of Spirit and Time</div><p class="paragraph">A collective longing across time zones, 2020<br><br>The Room of Spirit and Time is initiated by Taro Masushio, Xiaofei Mo, Ali Van, Wang Xu and Cici Wu. Taking the form of collaborative works and events, the first iteration at Queens Museum begins with readings of ancient and medieval Asian texts as a possible means to reimagine and cultivate a romantic epistemology. In this room, both learning and unlearning take place; we invite temporary amnesia, a kind of forgetting and drifting via exercises, recitations, meditations, improvisations... fluid and ephemeral sleepwalking. Along these activities are non - activities, where TRST functions as a hub for leisurely gatherings, for artists and thinkers, dreams and realities, set to a slow flow against the fast rhythms of New York City.<br><br><a href="http://theroomofspiritandtime.info/">link</a></p>',

  '<img src="./images/collaborations4.jpg"><div class="title">Lovers Revolt, Lovers Revolve&nbsp;&nbsp;<a href="#" style="font-size: 0.7em !important;">(PDF link)</a></div><p><em>Lovers Revolt, Lovers Revolve</em> traverses across the past lives and future lives, with a sentient mirror and a missing tooth playing important roles. The film is the second chapter of <em>Lovers Revolt Lovers Revolve: stories against dictators, colonizers, and all other monsters</em>, a collaborative fiction project with Cici Wu, consisting of video, works on paper, and an on-going series of publications.</p>',

]

function get_random_collaboration(){
  // Get a random index
  random_index = Math.floor(Math.random() * collaborations_array.length);

  // Get code using the random_index
  selected_code = collaborations_array[random_index]

  // Insert the code
  document.getElementById('wrapper').innerHTML = `${selected_code}`
}

// Memories
memories_array = [
  '<img src="./images/memories1.jpg"><p style="margin-bottom:100px;">logic class, photo from a classmate, 2007</p>',
  '<img src="./images/memories2.jpg"><p style="margin-bottom:100px;">a view from home, 2017</p>',
  '<video autoplay loop muted playsinline style="width:100%;"><source src="./images/memories3.mp4" type="video/mp4" /></video><p style="margin-bottom:100px;">pages from a sutra, 1999</div>',
  '<video autoplay loop muted playsinline style="width:100%;"><source src="./images/memories4.mp4" type="video/mp4" /></video><p style="margin-bottom:100px;">Charlie vs Charlie with friends, 2023</div>',
  '<img src="./images/memories5.jpg"><p style="margin-bottom:100px;">mother&#39s Day with Victor, 2021</p>',
  '<video autoplay loop muted playsinline style="width:100%;"><source src="./images/memories6.mp4" type="video/mp4" /></video><p style="margin-bottom:100px;">at night with POND, March 2016</div>',
]

function get_random_memories(){
  // Get a random index
  random_index = Math.floor(Math.random() * memories_array.length);

  // Get code using the random_index
  selected_code = memories_array[random_index]

  // Insert the code
  document.getElementById('wrapper').innerHTML = `${selected_code}`
}

function get_bio(){
  // Insert the code
  document.getElementById('wrapper').innerHTML = `<p style="padding:2% 0 0 0;">Xiaofei Mo is a filmmaker based in New York, whose work explores the possibilities and limits in communing with non-human sentient beings. She trains and works with an AI named POND (2016-present) to explore the porous nature of image and language, memory and feeling, friction and movement. POND have no mother tongue, they learn from and in translation, and grow organs without body. Her works were shown at Hordaland Kunstsenter, Bergen (2023), International Kurzfilmtage Winterthur (2021), Empty Gallery at Art Basel Hong Kong (2020), and c4 projects, Copenhagen (2019). She is a founding member of The Room of Spirit and Time, a collective reading group in residence at Queens Museum, New York (2018-2020), and has received grants from Goethe-Institut China (2018) among others.<br><br><a href="mailto:xiaofei.z.mo@gmail.com">xiaofei.z.mo@gmail.com</a></p>`
}